services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: config_parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bsdkqwsd123
    ports:
      - 5432:5432
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
